on: [push]

name: AzureStack AAD PowerShellSample

jobs:
  ci_job:
    runs-on: rakku-wd
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Use Local Azure Login Action
        uses: ./
        with:
          creds: ${{ secrets.AZURESTACK_LH01_AAD_CREDENTIALS }}
          profileVersion: 2019-03-01-hybrid
          customEnvironmentName: AzureStackLH001
          enable-AzPSSession: true
      - name: Run Azure CLI Script Against AzureStack
        run: |
          hostname
          az account show --output table
          az group list --output table
          az webapp list --output table
          az resource list --output table
      - name: Run Az PowerShell  Script Against AzureStack
        uses: azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            hostname
            Get-AzContext
            Get-AzResourceGroup
            Get-AzResource 