# File: .github/workflows/workflow.yml

on: [push]

name: Azure PowerShellSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
        npm run build
    - name: Use Local Azure Login Action
      uses: ./
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - name: Run Azure CLI Script
      run: |
        hostname
        az account show --output table
        az webapp list --output table
        az group list --output table
    - name: Run Azure PowerShell Script
      uses: azure/powershell@v1
      with:
        azPSVersion: '3.1.0'
        inlineScript: |
          hostname
          Get-AzContext
          Get-AzResourceGroup