on: [push]

name: AzureStack AAD PowerShellSample

jobs:
  ci_job:
    runs-on: rakku-wd
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Use Local Azure Login Action
        uses: ./
        with:
          creds: ${{ secrets.AZURESTACK_LH01_AAD_CREDENTIALS }}
          enable-AzPSSession: true
          environment: AzureStack
      - name: Run Azure CLI Script Against AzureStack
        run: |
          hostname
          az account show --output table
          az group list --output table
          az webapp list --output table
          az resource list --output table
          az keyvault create --location northwest --name 'keyvaulttest' --resource-group gha-lh01-rg
          az keyvault secret set --name 'testsecret' --vault-name 'keyvaulttest' --value 'sample'
          az storage account delete -n 'satest002' -g 'gha-lh01-rg' --yes
          az storage account create --location northwest --name 'satest002' --resource-group 'gha-lh01-rg' --sku Standard_LRS
          az storage container create -n 'testsacon001' --public-access container
      - name: Run Az PowerShell  Script Against AzureStack
        uses: azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            hostname
            Get-AzContext
            Get-AzResourceGroup
            Get-AzResource 